config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: 'home#index'
  get '/subscribe', to: 'posts#subscribe'
  get '/subscribers', to: 'posts#subscribers'
  get '/subscription', to: 'posts#subscribed'
  delete 'delete_subscriber/:id(.:format)', :to => 'posts#delete_subscriber', as: 'delete_subscriber'

  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :subscribers, :dependent => :destroy
  mount_uploader :photo, ImageUploader
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, :message => "Its already subscribed"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, :dependent => :destroy
  has_many :subscribers, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def subscribed
  end

  def subscribe
    subscriber = Subscriber.new
    subscriber.post_id = params[:subscribe][:post_id]
    subscriber.user_id = params[:subscribe][:user_id]
    if subscriber.save
      respond_to do |format|
        format.js {  flash[:notice] = "Subscribed successfully" }
        format.html { redirect_to posts_path, notice: 'Subscribed successfully.' }
      end
    end
  end

  def subscribers
    @subscribers = Subscriber.where(user_id: current_user.id)
  end

  def delete_subscriber
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Unsubscribed successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :photo, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to 'New Post', new_post_path, class: "nav-link btn btn-success btn-sm" if user_signed_in? %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Posts', posts_path, class: "nav-link btn btn-secondary btn-sm ml-2"%>
      </li>
      <li class="nav-item active">
        <%= link_to 'Subscribed Posts', subscribers_path, class: "nav-link btn btn-warning btn-sm ml-2" if user_signed_in? %>
      </li>
      <%if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link logout btn btn-danger btn-sm" %>
        </li>
      <%else%>
        <li class="nav-item active">
          <%= link_to 'LogIn', new_user_session_path, class: "nav-link btn btn-danger mr-2 btn-sm login" %>
        </li>
        <li class="nav-item active">
          <%= link_to 'SignUp', new_user_registration_path, class: "nav-link btn btn-danger btn-sm" %>
        </li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<div class="container justify-content-center mt-5">
    <div class="jumbotron my-auto text-center">
		<h1 class="display-5"> Photo Sharing Social Application </h1>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSharingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render partial: "home/header"%>
  	<% if notice.present? %>
      <div class="alert alert-success alert-dismissible styling ">
        <button type="button" class="close" data-dismiss="alert">&times;      </button>
  			<span class="text-center"><%= notice %></span>
      </div>
    <%else%>
    	<%if alert.present? %>
	    	<div class="alert alert-success alert-dismissible styling ">
	        <button type="button" class="close" data-dismiss="alert">&times;      </button>
	  			<span class="text-center"><%= alert%></span>
	      </div>
	  	<% end %>
    <% end%>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :photo %>
    <%= f.file_field :photo, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "submit" , class: "btn btn-success" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container justify-content-center login-width mt-5">
  <div class="jumbotron my-auto">
		<h3 class="text-center text-primary">Edit Post</h3>

		<%= render 'form', post: @post %>
		<br>
		<%= link_to 'Back', posts_path, class: "btn btn-primary" %>
	</div>
</div>

app/views/posts/index.html.erb
  <!-- <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%=image_tag(post.photo.url, alt: 'Image') if post.photo?%></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %> -->
<%if user_signed_in?%>
<h6 class="text-left text-secondary mt-2">You have created <%=current_user.posts.count%> Posts </h6>
<%end%>
<div class="container justify-content-center post-width mt-5">
  <div class="jumbotron my-auto">
    <%if @posts.present? %>
      <h3 class="text-center text-primary mb-5">Posts</h3>
      <% @posts.each do |post| %>
        <div class="ml-5 mb-1">
          <b class="text-secondary"><%= post.title.capitalize %></b> posted by <i class="font-weight-bold text-secondary"><%=post.user.name.capitalize%></i> created on <%= post.created_at.strftime "%A, %b %d" %>
        </div>
        <div class="text-center">
          <%=image_tag(post.photo.url, alt: 'Image', class: "border border-secondary rounded") if post.photo?%>
        </div>
        <div class="row col-4 ml-5 mt-1 ml-auto">
          <div class="col-md-1 ml-auto">
            <%if user_signed_in? && current_user == post.user %>
              <%= link_to edit_post_path(post), title: "Edit","data-toggle": "tooltip", "data-placement": "bottom" do %>
                <i class="fa fa-pencil-square"></i> 
              <%end%>
            <%end%>
          </div>
          <div class="col-md-1">
            <%if user_signed_in? && current_user == post.user %>
              <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete","data-toggle": "tooltip", "data-placement": "bottom" do %>
                <i class="fa fa-trash"></i>
              <%end%>
            <%end%>
          </div>
          <div class="col-md-1 mr-5">
            <%if user_signed_in? %>
              <% if current_user != post.user %>
                <a href="#", onclick="subscribe(<%= current_user.id %>, <%= post.id %>);", data-toggle="tooltip" data-placement="bottom" title="Subscribe">
                  <i class="fa fa-plus-square-o"></i>
                </a>
              <%end%>
            <%else%>
              <%=link_to subscription_path, title: "Subscribe", "data-toggle": "tooltip", "data-placement": "bottom" do %>
                <i class="fa fa-plus-square-o"></i>
              <%end%>
            <%end%>
          </div>
        </div>
        <br>
      <%end%>
    <%else%>
      <h4 class="text-center text-secondary">No posts have been created yet</h4>
    <%end%>
  </div>
</div>
<script type="text/javascript">
  function subscribe(user_id,post_id) {
  $.ajax({ 
       url: '/subscribe', 
       data: $.param({ subscribe: {user_id: user_id, post_id: post_id }})
  });
 }
</script>

app/views/posts/new.html.erb
<div class="container justify-content-center login-width mt-5">
  <div class="jumbotron my-auto">
		<h3 class="text-center text-primary">New Post</h3>

		<%= render 'form', post: @post %>
    <br>
		<%= link_to 'Back', posts_path, class: "btn btn-info" %>
	</div>
</div>

app/views/posts/subscribers.html.erb
<div class="container justify-content-center post-width mt-5">
  <div class="jumbotron my-auto">
    <%if @subscribers.present? %>
      <h3 class="text-center text-primary mb-5">Subscribed Posts</h3>
      <% @subscribers.each do |s| %>
        <% post = Post.find(s.post_id) %>
        <div class="ml-5 mb-1">
          <b class="text-secondary"><%= post.title.capitalize %></b> posted by <i class="font-weight-bold text-secondary"><%=post.user.name.capitalize%></i>
        </div>
        <div class="text-center">
          <%=image_tag(post.photo.url, alt: 'Image', class: "border border-secondary rounded") if post.photo?%>
        </div>
        <div class="row col-4 ml-5 mt-1 ml-auto">
          <div class="col-md-1 ml-auto">
            
          </div>
          <div class="col-md-1 mr-5">
            <%= link_to delete_subscriber_path(s), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fa fa-trash"></i>
            <%end%>
          </div>
        </div>
        <br>
      <%end%>
    <%else%>
      <h4 class="text-center text-secondary">No posts have been subscribed</h4>
    <%end%>
  </div>
</div>